spring:
  cache:
    type: redis
    redis:
      time-to-live: 36000000
      cache-null-values: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_database
    username: attyuttam
    password: attyuttam$123
    hikari:
      initialization-fail-timeout: 0
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

